import type { Metadata } from "next";
import { createClient } from "@/shared/api/server";
import { QueryProvider } from "@/app/providers/QueryProvider";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets/Header/ui/Header";
import { Footer } from "@widgets/footer/ui/Footer";

const geistSans = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins-sans",
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <Header user={user} />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
