import type { Metadata } from "next";
import { QueryProvider } from "@/app/providers/QueryProvider";
import { Poppins } from "next/font/google";
import "./globals.css";


const geistSans = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins-sans",
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html
      lang="en"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>    
            {children}    
        </QueryProvider>
      </body>
    </html>
  );
}
